// /projects/dkjfkl232kd/issues/dfksdjfl233k/comments
const commentsIssueEvent = {
  resource: '/projects/{projectId}/issues/{issueId}/comments',
  path: '/projects/dkjfkl232kd/issues/dfksdjfl233k/comments',
  httpMethod: 'GET',
  headers: null,
  multiValueHeaders: null,
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  pathParameters: { projectId: 'dkjfkl232kd', issueId: 'dfksdjfl233k' },
  stageVariables: null,
  requestContext: {
    resourceId: 'gfa9nd',
    resourcePath: '/projects/{projectId}/issues/{issueId}/comments',
    httpMethod: 'GET',
    extendedRequestId: 'WouWHEhKIAMFa2w=',
    requestTime: '10/Aug/2022:07:26:56 +0000',
    path: '/projects/{projectId}/issues/{issueId}/comments',
    accountId: '239344013128',
    protocol: 'HTTP/1.1',
    stage: 'test-invoke-stage',
    domainPrefix: 'testPrefix',
    requestTimeEpoch: 1660116416516,
    requestId: 'dfb97664-b29f-4972-a549-7a8db0e42559',
    identity: {
      cognitoIdentityPoolId: null,
      cognitoIdentityId: null,
      apiKey: 'test-invoke-api-key',
      principalOrgId: null,
      cognitoAuthenticationType: null,
      userArn: 'arn:aws:iam::239344013128:user/pengfei-development',
      apiKeyId: 'test-invoke-api-key-id',
      userAgent:
        'aws-internal/3 aws-sdk-java/1.12.239 Linux/5.4.196-119.356.amzn2int.x86_64 OpenJDK_64-Bit_Server_VM/25.332-b08 java/1.8.0_332 vendor/Oracle_Corporation cfg/retry-mode/standard',
      accountId: '239344013128',
      caller: 'AIDATPOQDZ5EKU5UILZZM',
      sourceIp: 'test-invoke-source-ip',
      accessKey: 'ASIATPOQDZ5EFRSKM2JQ',
      cognitoAuthenticationProvider: null,
      user: 'AIDATPOQDZ5EKU5UILZZM',
    },
    domainName: 'testPrefix.testDomainName',
    apiId: 'kd3nfw7wqc',
  },
  body: null,
  isBase64Encoded: false,
};

// /projects/djfksdlj32/issues/djfkdlj23/comments - POST
const commentAddEvent = {
  resource: '/projects/{projectId}/issues/{issueId}/comments',
  path: '/projects/djfksdlj32/issues/djfkdlj23/comments',
  httpMethod: 'POST',
  headers: null,
  multiValueHeaders: null,
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  pathParameters: { projectId: 'djfksdlj32', issueId: 'djfkdlj23' },
  stageVariables: null,
  requestContext: {
    resourceId: 'gfa9nd',
    resourcePath: '/projects/{projectId}/issues/{issueId}/comments',
    httpMethod: 'POST',
    extendedRequestId: 'WouppHFroAMFpHA=',
    requestTime: '10/Aug/2022:07:29:01 +0000',
    path: '/projects/{projectId}/issues/{issueId}/comments',
    accountId: '239344013128',
    protocol: 'HTTP/1.1',
    stage: 'test-invoke-stage',
    domainPrefix: 'testPrefix',
    requestTimeEpoch: 1660116541592,
    requestId: '25d50baa-0938-4da1-9a6b-9e1bedde1bb4',
    identity: {
      cognitoIdentityPoolId: null,
      cognitoIdentityId: null,
      apiKey: 'test-invoke-api-key',
      principalOrgId: null,
      cognitoAuthenticationType: null,
      userArn: 'arn:aws:iam::239344013128:user/pengfei-development',
      apiKeyId: 'test-invoke-api-key-id',
      userAgent:
        'aws-internal/3 aws-sdk-java/1.12.239 Linux/5.4.196-119.356.amzn2int.x86_64 OpenJDK_64-Bit_Server_VM/25.332-b08 java/1.8.0_332 vendor/Oracle_Corporation cfg/retry-mode/standard',
      accountId: '239344013128',
      caller: 'AIDATPOQDZ5EKU5UILZZM',
      sourceIp: 'test-invoke-source-ip',
      accessKey: 'ASIATPOQDZ5EFRSKM2JQ',
      cognitoAuthenticationProvider: null,
      user: 'AIDATPOQDZ5EKU5UILZZM',
    },
    domainName: 'testPrefix.testDomainName',
    apiId: 'kd3nfw7wqc',
  },
  body: '{"content": "test comment"}',
  isBase64Encoded: false,
};

// /projects/jdfkj32jd/issues/kkjfie293/comments/dfkjkdfj23d - PUT
const updateCommentEvent = {
  resource: '/projects/{projectId}/issues/{issueId}/comments/{commentId}',
  path: '/projects/jdfkj32jd/issues/kkjfie293/comments/dfkjkdfj23d',
  httpMethod: 'PUT',
  headers: null,
  multiValueHeaders: null,
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  pathParameters: {
    commentId: 'dfkjkdfj23d',
    issueId: 'kkjfie293',
    projectId: 'jdfkj32jd',
  },
  stageVariables: null,
  requestContext: {
    resourceId: '1b4zyn',
    resourcePath: '/projects/{projectId}/issues/{issueId}/comments/{commentId}',
    httpMethod: 'PUT',
    extendedRequestId: 'Wou99GT2oAMFUWQ=',
    requestTime: '10/Aug/2022:07:31:11 +0000',
    path: '/projects/{projectId}/issues/{issueId}/comments/{commentId}',
    accountId: '239344013128',
    protocol: 'HTTP/1.1',
    stage: 'test-invoke-stage',
    domainPrefix: 'testPrefix',
    requestTimeEpoch: 1660116671563,
    requestId: '0fa7c939-3584-45a6-8a1f-8a6e69d38b5b',
    identity: {
      cognitoIdentityPoolId: null,
      cognitoIdentityId: null,
      apiKey: 'test-invoke-api-key',
      principalOrgId: null,
      cognitoAuthenticationType: null,
      userArn: 'arn:aws:iam::239344013128:user/pengfei-development',
      apiKeyId: 'test-invoke-api-key-id',
      userAgent:
        'aws-internal/3 aws-sdk-java/1.12.239 Linux/5.4.196-119.356.amzn2int.x86_64 OpenJDK_64-Bit_Server_VM/25.332-b08 java/1.8.0_332 vendor/Oracle_Corporation cfg/retry-mode/standard',
      accountId: '239344013128',
      caller: 'AIDATPOQDZ5EKU5UILZZM',
      sourceIp: 'test-invoke-source-ip',
      accessKey: 'ASIATPOQDZ5EFRSKM2JQ',
      cognitoAuthenticationProvider: null,
      user: 'AIDATPOQDZ5EKU5UILZZM',
    },
    domainName: 'testPrefix.testDomainName',
    apiId: 'kd3nfw7wqc',
  },
  body: '{"content": "test2"}',
  isBase64Encoded: false,
};

// /projects/3j34kll22/issues/dfjkdj29/comments/djkfjk32k - Delete
const deleteCommentEvent = {
  resource: '/projects/{projectId}/issues/{issueId}/comments/{commentId}',
  path: '/projects/3j34kll22/issues/dfjkdj29/comments/djkfjk32k',
  httpMethod: 'DELETE',
  headers: null,
  multiValueHeaders: null,
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  pathParameters: {
    commentId: 'djkfjk32k',
    issueId: 'dfjkdj29',
    projectId: '3j34kll22',
  },
  stageVariables: null,
  requestContext: {
    resourceId: '1b4zyn',
    resourcePath: '/projects/{projectId}/issues/{issueId}/comments/{commentId}',
    httpMethod: 'DELETE',
    extendedRequestId: 'WovMLGsMIAMF5kA=',
    requestTime: '10/Aug/2022:07:32:42 +0000',
    path: '/projects/{projectId}/issues/{issueId}/comments/{commentId}',
    accountId: '239344013128',
    protocol: 'HTTP/1.1',
    stage: 'test-invoke-stage',
    domainPrefix: 'testPrefix',
    requestTimeEpoch: 1660116762540,
    requestId: 'd27df28d-6e12-4c31-84a1-c7825017cc47',
    identity: {
      cognitoIdentityPoolId: null,
      cognitoIdentityId: null,
      apiKey: 'test-invoke-api-key',
      principalOrgId: null,
      cognitoAuthenticationType: null,
      userArn: 'arn:aws:iam::239344013128:user/pengfei-development',
      apiKeyId: 'test-invoke-api-key-id',
      userAgent:
        'aws-internal/3 aws-sdk-java/1.12.239 Linux/5.4.196-119.356.amzn2int.x86_64 OpenJDK_64-Bit_Server_VM/25.332-b08 java/1.8.0_332 vendor/Oracle_Corporation cfg/retry-mode/standard',
      accountId: '239344013128',
      caller: 'AIDATPOQDZ5EKU5UILZZM',
      sourceIp: 'test-invoke-source-ip',
      accessKey: 'ASIATPOQDZ5EFRSKM2JQ',
      cognitoAuthenticationProvider: null,
      user: 'AIDATPOQDZ5EKU5UILZZM',
    },
    domainName: 'testPrefix.testDomainName',
    apiId: 'kd3nfw7wqc',
  },
  body: null,
  isBase64Encoded: false,
};
