// /projects/djfkldsjfkl234/issues/dfdjkfl2jkdfj/history - GET
const historyIssueEvent = {
  resource: '/projects/{projectId}/issues/{issueId}/history',
  path: '/projects/djfkldsjfkl234/issues/dfdjkfl2jkdfj/history',
  httpMethod: 'GET',
  headers: null,
  multiValueHeaders: null,
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  pathParameters: { projectId: 'djfkldsjfkl234', issueId: 'dfdjkfl2jkdfj' },
  stageVariables: null,
  requestContext: {
    resourceId: 'ra0kni',
    resourcePath: '/projects/{projectId}/issues/{issueId}/history',
    httpMethod: 'GET',
    extendedRequestId: 'WovnpFScoAMFtJg=',
    requestTime: '10/Aug/2022:07:35:38 +0000',
    path: '/projects/{projectId}/issues/{issueId}/history',
    accountId: '239344013128',
    protocol: 'HTTP/1.1',
    stage: 'test-invoke-stage',
    domainPrefix: 'testPrefix',
    requestTimeEpoch: 1660116938368,
    requestId: 'cb7333fe-5221-48cf-92e7-eb7dddace1e2',
    identity: {
      cognitoIdentityPoolId: null,
      cognitoIdentityId: null,
      apiKey: 'test-invoke-api-key',
      principalOrgId: null,
      cognitoAuthenticationType: null,
      userArn: 'arn:aws:iam::239344013128:user/pengfei-development',
      apiKeyId: 'test-invoke-api-key-id',
      userAgent:
        'aws-internal/3 aws-sdk-java/1.12.239 Linux/5.4.196-119.356.amzn2int.x86_64 OpenJDK_64-Bit_Server_VM/25.332-b08 java/1.8.0_332 vendor/Oracle_Corporation cfg/retry-mode/standard',
      accountId: '239344013128',
      caller: 'AIDATPOQDZ5EKU5UILZZM',
      sourceIp: 'test-invoke-source-ip',
      accessKey: 'ASIATPOQDZ5EEG6PIMZH',
      cognitoAuthenticationProvider: null,
      user: 'AIDATPOQDZ5EKU5UILZZM',
    },
    domainName: 'testPrefix.testDomainName',
    apiId: 'kd3nfw7wqc',
  },
  body: null,
  isBase64Encoded: false,
};

// /projects/djfkl23kj/issues/dfdfkljsdk2/history - POST
const addHistoryEvent = {
  resource: '/projects/{projectId}/issues/{issueId}/history',
  path: '/projects/djfkl23kj/issues/dfdfkljsdk2/history',
  httpMethod: 'POST',
  headers: null,
  multiValueHeaders: null,
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  pathParameters: { projectId: 'djfkl23kj', issueId: 'dfdfkljsdk2' },
  stageVariables: null,
  requestContext: {
    resourceId: 'ra0kni',
    resourcePath: '/projects/{projectId}/issues/{issueId}/history',
    httpMethod: 'POST',
    extendedRequestId: 'Wov5sETPIAMFaoQ=',
    requestTime: '10/Aug/2022:07:37:33 +0000',
    path: '/projects/{projectId}/issues/{issueId}/history',
    accountId: '239344013128',
    protocol: 'HTTP/1.1',
    stage: 'test-invoke-stage',
    domainPrefix: 'testPrefix',
    requestTimeEpoch: 1660117053835,
    requestId: 'b7da7fd1-d586-4e30-801f-081303cc91aa',
    identity: {
      cognitoIdentityPoolId: null,
      cognitoIdentityId: null,
      apiKey: 'test-invoke-api-key',
      principalOrgId: null,
      cognitoAuthenticationType: null,
      userArn: 'arn:aws:iam::239344013128:user/pengfei-development',
      apiKeyId: 'test-invoke-api-key-id',
      userAgent:
        'aws-internal/3 aws-sdk-java/1.12.239 Linux/5.4.196-119.356.amzn2int.x86_64 OpenJDK_64-Bit_Server_VM/25.332-b08 java/1.8.0_332 vendor/Oracle_Corporation cfg/retry-mode/standard',
      accountId: '239344013128',
      caller: 'AIDATPOQDZ5EKU5UILZZM',
      sourceIp: 'test-invoke-source-ip',
      accessKey: 'ASIATPOQDZ5EEG6PIMZH',
      cognitoAuthenticationProvider: null,
      user: 'AIDATPOQDZ5EKU5UILZZM',
    },
    domainName: 'testPrefix.testDomainName',
    apiId: 'kd3nfw7wqc',
  },
  body: '{"field": "Issue"}',
  isBase64Encoded: false,
};
