// /people - GET
const allPeopleEvent = {
  resource: '/people',
  path: '/people',
  httpMethod: 'GET',
  headers: null,
  multiValueHeaders: null,
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  pathParameters: null,
  stageVariables: null,
  requestContext: {
    resourceId: 'aaihm2',
    resourcePath: '/people',
    httpMethod: 'GET',
    extendedRequestId: 'WoieAHbJIAMFv-Q=',
    requestTime: '10/Aug/2022:06:05:51 +0000',
    path: '/people',
    accountId: '239344013128',
    protocol: 'HTTP/1.1',
    stage: 'test-invoke-stage',
    domainPrefix: 'testPrefix',
    requestTimeEpoch: 1660111551891,
    requestId: 'dbb895f7-d9de-405e-a610-b5c57490764f',
    identity: {
      cognitoIdentityPoolId: null,
      cognitoIdentityId: null,
      apiKey: 'test-invoke-api-key',
      principalOrgId: null,
      cognitoAuthenticationType: null,
      userArn: 'arn:aws:iam::239344013128:user/pengfei-development',
      apiKeyId: 'test-invoke-api-key-id',
      userAgent:
        'aws-internal/3 aws-sdk-java/1.12.239 Linux/5.4.196-119.356.amzn2int.x86_64 OpenJDK_64-Bit_Server_VM/25.332-b08 java/1.8.0_332 vendor/Oracle_Corporation cfg/retry-mode/standard',
      accountId: '239344013128',
      caller: 'AIDATPOQDZ5EKU5UILZZM',
      sourceIp: 'test-invoke-source-ip',
      accessKey: 'ASIATPOQDZ5EFRSKM2JQ',
      cognitoAuthenticationProvider: null,
      user: 'AIDATPOQDZ5EKU5UILZZM',
    },
    domainName: 'testPrefix.testDomainName',
    apiId: 'kd3nfw7wqc',
  },
  body: null,
  isBase64Encoded: false,
};

// /people?status=Active - GET
const activePeopleEvent = {
  resource: '/people',
  path: '/people',
  httpMethod: 'GET',
  headers: null,
  multiValueHeaders: null,
  queryStringParameters: { status: 'Active' },
  multiValueQueryStringParameters: { status: ['Active'] },
  pathParameters: null,
  stageVariables: null,
  requestContext: {
    resourceId: 'aaihm2',
    resourcePath: '/people',
    httpMethod: 'GET',
    extendedRequestId: 'Woj5wEEaoAMFVkw=',
    requestTime: '10/Aug/2022:06:15:39 +0000',
    path: '/people',
    accountId: '239344013128',
    protocol: 'HTTP/1.1',
    stage: 'test-invoke-stage',
    domainPrefix: 'testPrefix',
    requestTimeEpoch: 1660112139090,
    requestId: 'ec6af065-49e2-45e9-ba72-991f9b5b7fec',
    identity: {
      cognitoIdentityPoolId: null,
      cognitoIdentityId: null,
      apiKey: 'test-invoke-api-key',
      principalOrgId: null,
      cognitoAuthenticationType: null,
      userArn: 'arn:aws:iam::239344013128:user/pengfei-development',
      apiKeyId: 'test-invoke-api-key-id',
      userAgent:
        'aws-internal/3 aws-sdk-java/1.12.239 Linux/5.4.196-119.356.amzn2int.x86_64 OpenJDK_64-Bit_Server_VM/25.332-b08 java/1.8.0_332 vendor/Oracle_Corporation cfg/retry-mode/standard',
      accountId: '239344013128',
      caller: 'AIDATPOQDZ5EKU5UILZZM',
      sourceIp: 'test-invoke-source-ip',
      accessKey: 'ASIATPOQDZ5EFRSKM2JQ',
      cognitoAuthenticationProvider: null,
      user: 'AIDATPOQDZ5EKU5UILZZM',
    },
    domainName: 'testPrefix.testDomainName',
    apiId: 'kd3nfw7wqc',
  },
  body: null,
  isBase64Encoded: false,
};

// /people - POST
const peopleAddEvent = {
  resource: '/people',
  path: '/people',
  httpMethod: 'POST',
  headers: null,
  multiValueHeaders: null,
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  pathParameters: null,
  stageVariables: null,
  requestContext: {
    resourceId: 'aaihm2',
    resourcePath: '/people',
    httpMethod: 'POST',
    extendedRequestId: 'WotEiHZsoAMFYsA=',
    requestTime: '10/Aug/2022:07:18:14 +0000',
    path: '/people',
    accountId: '239344013128',
    protocol: 'HTTP/1.1',
    stage: 'test-invoke-stage',
    domainPrefix: 'testPrefix',
    requestTimeEpoch: 1660115894441,
    requestId: '908ada74-73fc-4255-a79d-24e130932c31',
    identity: {
      cognitoIdentityPoolId: null,
      cognitoIdentityId: null,
      apiKey: 'test-invoke-api-key',
      principalOrgId: null,
      cognitoAuthenticationType: null,
      userArn: 'arn:aws:iam::239344013128:user/pengfei-development',
      apiKeyId: 'test-invoke-api-key-id',
      userAgent:
        'aws-internal/3 aws-sdk-java/1.12.239 Linux/5.4.196-119.356.amzn2int.x86_64 OpenJDK_64-Bit_Server_VM/25.332-b08 java/1.8.0_332 vendor/Oracle_Corporation cfg/retry-mode/standard',
      accountId: '239344013128',
      caller: 'AIDATPOQDZ5EKU5UILZZM',
      sourceIp: 'test-invoke-source-ip',
      accessKey: 'ASIATPOQDZ5EFRSKM2JQ',
      cognitoAuthenticationProvider: null,
      user: 'AIDATPOQDZ5EKU5UILZZM',
    },
    domainName: 'testPrefix.testDomainName',
    apiId: 'kd3nfw7wqc',
  },
  body: '{"email": "john@gmail.com"}',
  isBase64Encoded: false,
};

// /people/john@gmail.com - PUT
const peopleUpdateEvent = {
  resource: '/people/{email}',
  path: '/people/john@gmail.com',
  httpMethod: 'PUT',
  headers: null,
  multiValueHeaders: null,
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  pathParameters: { email: 'john@gmail.com' },
  stageVariables: null,
  requestContext: {
    resourceId: 'k0k4o2',
    resourcePath: '/people/{email}',
    httpMethod: 'PUT',
    extendedRequestId: 'WomJTHsZoAMFcJA=',
    requestTime: '10/Aug/2022:06:30:57 +0000',
    path: '/people/{email}',
    accountId: '239344013128',
    protocol: 'HTTP/1.1',
    stage: 'test-invoke-stage',
    domainPrefix: 'testPrefix',
    requestTimeEpoch: 1660113057795,
    requestId: 'c1b328f4-8a65-4a27-9dfb-422744d913d2',
    identity: {
      cognitoIdentityPoolId: null,
      cognitoIdentityId: null,
      apiKey: 'test-invoke-api-key',
      principalOrgId: null,
      cognitoAuthenticationType: null,
      userArn: 'arn:aws:iam::239344013128:user/pengfei-development',
      apiKeyId: 'test-invoke-api-key-id',
      userAgent:
        'aws-internal/3 aws-sdk-java/1.12.239 Linux/5.4.196-119.356.amzn2int.x86_64 OpenJDK_64-Bit_Server_VM/25.332-b08 java/1.8.0_332 vendor/Oracle_Corporation cfg/retry-mode/standard',
      accountId: '239344013128',
      caller: 'AIDATPOQDZ5EKU5UILZZM',
      sourceIp: 'test-invoke-source-ip',
      accessKey: 'ASIATPOQDZ5EFRSKM2JQ',
      cognitoAuthenticationProvider: null,
      user: 'AIDATPOQDZ5EKU5UILZZM',
    },
    domainName: 'testPrefix.testDomainName',
    apiId: 'kd3nfw7wqc',
  },
  body: `{email: "john@gmail.com", status: 'Active'}`,
  isBase64Encoded: false,
};

// /people/john@gmail.com/issues  - GET
const peopleIssuesEvent = {
  resource: '/people/{email}/issues',
  path: '/people/john@gmail.com/issues',
  httpMethod: 'GET',
  headers: null,
  multiValueHeaders: null,
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  pathParameters: { email: 'john@gmail.com' },
  stageVariables: null,
  requestContext: {
    resourceId: '2ojh2b',
    resourcePath: '/people/{email}/issues',
    httpMethod: 'GET',
    extendedRequestId: 'Wom-2HIsoAMFggw=',
    requestTime: '10/Aug/2022:06:36:40 +0000',
    path: '/people/{email}/issues',
    accountId: '239344013128',
    protocol: 'HTTP/1.1',
    stage: 'test-invoke-stage',
    domainPrefix: 'testPrefix',
    requestTimeEpoch: 1660113400449,
    requestId: '491a40c5-0d4f-41ff-a9e0-42770a71bf07',
    identity: {
      cognitoIdentityPoolId: null,
      cognitoIdentityId: null,
      apiKey: 'test-invoke-api-key',
      principalOrgId: null,
      cognitoAuthenticationType: null,
      userArn: 'arn:aws:iam::239344013128:user/pengfei-development',
      apiKeyId: 'test-invoke-api-key-id',
      userAgent:
        'aws-internal/3 aws-sdk-java/1.12.239 Linux/5.4.196-119.356.amzn2int.x86_64 OpenJDK_64-Bit_Server_VM/25.332-b08 java/1.8.0_332 vendor/Oracle_Corporation cfg/retry-mode/standard',
      accountId: '239344013128',
      caller: 'AIDATPOQDZ5EKU5UILZZM',
      sourceIp: 'test-invoke-source-ip',
      accessKey: 'ASIATPOQDZ5EFRSKM2JQ',
      cognitoAuthenticationProvider: null,
      user: 'AIDATPOQDZ5EKU5UILZZM',
    },
    domainName: 'testPrefix.testDomainName',
    apiId: 'kd3nfw7wqc',
  },
  body: null,
  isBase64Encoded: false,
};
