// /projects - GET
const getAllProjectsEvent = {
  resource: '/projects',
  path: '/projects',
  httpMethod: 'GET',
  headers: null,
  multiValueHeaders: null,
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  pathParameters: null,
  stageVariables: null,
  requestContext: {
    resourceId: 'dtdv1x',
    resourcePath: '/projects',
    httpMethod: 'GET',
    extendedRequestId: 'WooNuEjJoAMFWKw=',
    requestTime: '10/Aug/2022:06:45:05 +0000',
    path: '/projects',
    accountId: '239344013128',
    protocol: 'HTTP/1.1',
    stage: 'test-invoke-stage',
    domainPrefix: 'testPrefix',
    requestTimeEpoch: 1660113905252,
    requestId: 'd963d14b-978c-491d-aebe-a426cdc9256f',
    identity: {
      cognitoIdentityPoolId: null,
      cognitoIdentityId: null,
      apiKey: 'test-invoke-api-key',
      principalOrgId: null,
      cognitoAuthenticationType: null,
      userArn: 'arn:aws:iam::239344013128:user/pengfei-development',
      apiKeyId: 'test-invoke-api-key-id',
      userAgent:
        'aws-internal/3 aws-sdk-java/1.12.239 Linux/5.4.196-119.356.amzn2int.x86_64 OpenJDK_64-Bit_Server_VM/25.332-b08 java/1.8.0_332 vendor/Oracle_Corporation cfg/retry-mode/standard',
      accountId: '239344013128',
      caller: 'AIDATPOQDZ5EKU5UILZZM',
      sourceIp: 'test-invoke-source-ip',
      accessKey: 'ASIATPOQDZ5EFRSKM2JQ',
      cognitoAuthenticationProvider: null,
      user: 'AIDATPOQDZ5EKU5UILZZM',
    },
    domainName: 'testPrefix.testDomainName',
    apiId: 'kd3nfw7wqc',
  },
  body: null,
  isBase64Encoded: false,
};

//  /projects - Post
const addProjectEvent = {
  resource: '/projects',
  path: '/projects',
  httpMethod: 'POST',
  headers: null,
  multiValueHeaders: null,
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  pathParameters: null,
  stageVariables: null,
  requestContext: {
    resourceId: 'dtdv1x',
    resourcePath: '/projects',
    httpMethod: 'POST',
    extendedRequestId: 'WootwGKcIAMFs2Q=',
    requestTime: '10/Aug/2022:06:48:30 +0000',
    path: '/projects',
    accountId: '239344013128',
    protocol: 'HTTP/1.1',
    stage: 'test-invoke-stage',
    domainPrefix: 'testPrefix',
    requestTimeEpoch: 1660114110243,
    requestId: '7d356429-2e0b-40db-a647-1bde10973930',
    identity: {
      cognitoIdentityPoolId: null,
      cognitoIdentityId: null,
      apiKey: 'test-invoke-api-key',
      principalOrgId: null,
      cognitoAuthenticationType: null,
      userArn: 'arn:aws:iam::239344013128:user/pengfei-development',
      apiKeyId: 'test-invoke-api-key-id',
      userAgent:
        'aws-internal/3 aws-sdk-java/1.12.239 Linux/5.4.196-119.356.amzn2int.x86_64 OpenJDK_64-Bit_Server_VM/25.332-b08 java/1.8.0_332 vendor/Oracle_Corporation cfg/retry-mode/standard',
      accountId: '239344013128',
      caller: 'AIDATPOQDZ5EKU5UILZZM',
      sourceIp: 'test-invoke-source-ip',
      accessKey: 'ASIATPOQDZ5EFRSKM2JQ',
      cognitoAuthenticationProvider: null,
      user: 'AIDATPOQDZ5EKU5UILZZM',
    },
    domainName: 'testPrefix.testDomainName',
    apiId: 'kd3nfw7wqc',
  },
  body: '{"id": "12323123dfjsdk", "name": "project1"}',
  isBase64Encoded: false,
};

//  /projects/djkd03293jkfj - GET
const getProjectEvent = {
  resource: '/projects/{projectId}',
  path: '/projects/djkd03293jkfj',
  httpMethod: 'GET',
  headers: null,
  multiValueHeaders: null,
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  pathParameters: { projectId: 'djkd03293jkfj' },
  stageVariables: null,
  requestContext: {
    resourceId: 'sik1b7',
    resourcePath: '/projects/{projectId}',
    httpMethod: 'GET',
    extendedRequestId: 'WopH3EEXIAMFVTA=',
    requestTime: '10/Aug/2022:06:51:17 +0000',
    path: '/projects/{projectId}',
    accountId: '239344013128',
    protocol: 'HTTP/1.1',
    stage: 'test-invoke-stage',
    domainPrefix: 'testPrefix',
    requestTimeEpoch: 1660114277372,
    requestId: 'b657afc1-94ac-488b-875b-d566988d79fa',
    identity: {
      cognitoIdentityPoolId: null,
      cognitoIdentityId: null,
      apiKey: 'test-invoke-api-key',
      principalOrgId: null,
      cognitoAuthenticationType: null,
      userArn: 'arn:aws:iam::239344013128:user/pengfei-development',
      apiKeyId: 'test-invoke-api-key-id',
      userAgent:
        'aws-internal/3 aws-sdk-java/1.12.239 Linux/5.4.196-119.356.amzn2int.x86_64 OpenJDK_64-Bit_Server_VM/25.332-b08 java/1.8.0_332 vendor/Oracle_Corporation cfg/retry-mode/standard',
      accountId: '239344013128',
      caller: 'AIDATPOQDZ5EKU5UILZZM',
      sourceIp: 'test-invoke-source-ip',
      accessKey: 'ASIATPOQDZ5EFRSKM2JQ',
      cognitoAuthenticationProvider: null,
      user: 'AIDATPOQDZ5EKU5UILZZM',
    },
    domainName: 'testPrefix.testDomainName',
    apiId: 'kd3nfw7wqc',
  },
  body: null,
  isBase64Encoded: false,
};

// /projects/3kjdklsfji322 - PUT
const updateProjectEvent = {
  resource: '/projects/{projectId}',
  path: '/projects/3kjdklsfji322',
  httpMethod: 'PUT',
  headers: null,
  multiValueHeaders: null,
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  pathParameters: { projectId: '3kjdklsfji322' },
  stageVariables: null,
  requestContext: {
    resourceId: 'sik1b7',
    resourcePath: '/projects/{projectId}',
    httpMethod: 'PUT',
    extendedRequestId: 'Wopt9HWAoAMFcJA=',
    requestTime: '10/Aug/2022:06:55:21 +0000',
    path: '/projects/{projectId}',
    accountId: '239344013128',
    protocol: 'HTTP/1.1',
    stage: 'test-invoke-stage',
    domainPrefix: 'testPrefix',
    requestTimeEpoch: 1660114521135,
    requestId: '09662773-5498-40bd-bf44-cf299907af58',
    identity: {
      cognitoIdentityPoolId: null,
      cognitoIdentityId: null,
      apiKey: 'test-invoke-api-key',
      principalOrgId: null,
      cognitoAuthenticationType: null,
      userArn: 'arn:aws:iam::239344013128:user/pengfei-development',
      apiKeyId: 'test-invoke-api-key-id',
      userAgent:
        'aws-internal/3 aws-sdk-java/1.12.239 Linux/5.4.196-119.356.amzn2int.x86_64 OpenJDK_64-Bit_Server_VM/25.332-b08 java/1.8.0_332 vendor/Oracle_Corporation cfg/retry-mode/standard',
      accountId: '239344013128',
      caller: 'AIDATPOQDZ5EKU5UILZZM',
      sourceIp: 'test-invoke-source-ip',
      accessKey: 'ASIATPOQDZ5EFRSKM2JQ',
      cognitoAuthenticationProvider: null,
      user: 'AIDATPOQDZ5EKU5UILZZM',
    },
    domainName: 'testPrefix.testDomainName',
    apiId: 'kd3nfw7wqc',
  },
  body: '{"name": "project123"}',
  isBase64Encoded: false,
};

// /projects/jkdfljskj32jkd - Delete
const deleteProjectEvent = {
  resource: '/projects/{projectId}',
  path: '/projects/jkdfljskj32jkd',
  httpMethod: 'DELETE',
  headers: null,
  multiValueHeaders: null,
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  pathParameters: { projectId: 'jkdfljskj32jkd' },
  stageVariables: null,
  requestContext: {
    resourceId: 'sik1b7',
    resourcePath: '/projects/{projectId}',
    httpMethod: 'DELETE',
    extendedRequestId: 'Wop_DGhXoAMF7dg=',
    requestTime: '10/Aug/2022:06:57:10 +0000',
    path: '/projects/{projectId}',
    accountId: '239344013128',
    protocol: 'HTTP/1.1',
    stage: 'test-invoke-stage',
    domainPrefix: 'testPrefix',
    requestTimeEpoch: 1660114630576,
    requestId: '93ac9eef-f82b-4454-b7a7-6cbd781706a3',
    identity: {
      cognitoIdentityPoolId: null,
      cognitoIdentityId: null,
      apiKey: 'test-invoke-api-key',
      principalOrgId: null,
      cognitoAuthenticationType: null,
      userArn: 'arn:aws:iam::239344013128:user/pengfei-development',
      apiKeyId: 'test-invoke-api-key-id',
      userAgent:
        'aws-internal/3 aws-sdk-java/1.12.239 Linux/5.4.196-119.356.amzn2int.x86_64 OpenJDK_64-Bit_Server_VM/25.332-b08 java/1.8.0_332 vendor/Oracle_Corporation cfg/retry-mode/standard',
      accountId: '239344013128',
      caller: 'AIDATPOQDZ5EKU5UILZZM',
      sourceIp: 'test-invoke-source-ip',
      accessKey: 'ASIATPOQDZ5EFRSKM2JQ',
      cognitoAuthenticationProvider: null,
      user: 'AIDATPOQDZ5EKU5UILZZM',
    },
    domainName: 'testPrefix.testDomainName',
    apiId: 'kd3nfw7wqc',
  },
  body: null,
  isBase64Encoded: false,
};
